services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: awsalespassword
      POSTGRES_USER: awsales
      POSTGRES_DB: campaign
    ports:
      - 5432:5432
volumes:
  pgdata: